### ISSUE TITLE
CORS Pre-flight check failing

### ISSUE THREAD

**Issue by Jehanzeb-Malik** [woocommerce/woocommerce-rest-api-js-lib#15]
**What I'm trying to do:**
Im trying to update meta_data of a product. Below is the sample code

```
import WooCommerceRestApi from '@woocommerce/woocommerce-rest-api';

const WC = new WooCommerceRestApi({
  url: 'http://localhost:8888/wordpress', // Your store URL
  consumerKey: <key>, // Your consumer key
  consumerSecret: <secret>, // Your consumer secret
  version: 'wc/v3', // WooCommerce WP REST API version
});

export const fetchProducts = () => new Promise((resolve, reject) => {
  const params = {
    per_page: 50,
    meta: true,
  };

  WC.get('products', params).then((response) => {
    resolve(response.data);
  }).catch((error) => {
    reject(error.response.data);
  });
});

export const updateProduct = (id, data) => new Promise((resolve, reject) => {
  // data param contains an object {meta_data: [{},{},....,{}]}
  WC.put(`products/${id}`, data).then((response) => {
    console.log(response.data);
    resolve(response.data);
  }).catch((error) => {
    console.log(error);
    reject();
  });
})
```

I am able to fetch products without any issues through get request. But when I try to update `meta_data`, I get following error.

> Access to XMLHttpRequest at 'http://localhost:8888/wordpress/wp-json/wc/v3/products/816?oauth_consumer_key=1111222233334444&oauth_nonce=E3kDMWQOzCMwnmq1fFQR2QKNpETKdRYW&oauth_signature_method=HMAC-SHA256&oauth_timestamp=1566826887&oauth_version=1.0&oauth_signature=b05%2FvJVrAANDckfdPnjOpLJDmYVdtxBJNifGwYIgkHk%3D' from origin 'http://localhost:3000' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: It does not have HTTP ok status.

Can you please help me get through this. Regards.

**Comment by claudiosanches** [comment]
CORS policy is configured on your server, or in the browser in some cases, I found this guides that may help you:

- https://crunchify.com/how-to-fix-access-control-allow-origin-issue-for-your-https-enabled-wordpress-site-and-maxcdn/
- https://stackoverflow.com/questions/46522749/how-to-solve-redirect-has-been-blocked-by-cors-policy-no-access-control-allow

Still something that can't be by passed on this library, so you need to fix on your end.
