### ISSUE TITLE
I have error when send "GET"

### ISSUE THREAD

**Issue by AbdallaMohammed** [woocommerce/woocommerce-rest-api-js-lib#34]
"Refused to set unsafe header "User-Agent""

iam using vuejs

**Comment by claudiosanches** [comment]
Do you have more details about it?
You also can change the user-agent on your end setting a custom one using `axiosConfig`.

**Comment by Yzmx1995** [comment]
注释源码里的header设置可以解决，暂时没看的太大的问题，，增加axiosConfig好像会造成没有权限的问题,接口失败

**Comment by climba03003** [comment]
@claudiosanches @AbdallaMohammed 
It is more like a upstream issue with [axios](https://github.com/axios) or browser, you can discover in https://github.com/axios/axios/issues/1231. The main reason is that in the browser environment. Browser will block any action of changing the "User-Agent" header and throw an exception.

Possible solution will be check the usage environment and if it is browser environment then remove the "User-Agent" header.

**Comment by czlinNYC** [comment]
Im still getting this error

**Comment by czlinNYC** [comment]
> Do you have more details about it?
> You also can change the user-agent on your end setting a custom one using `axiosConfig`.

how does one go about doing it?
axiosConfig: { 'User-Agent': 'YOUR SERVICE HERE' }
unsure what to put in the your service here? how do i check my service name?

**Comment by raikusy** [comment]
I am still getting this error. In chrome it shows an error in console. in Safari the data isn't loaded. iPhone cannot load data because of this.
Can anyone help with this?

**Comment by GiuB** [comment]
I found a decent fix using axios interceptor to force removing custom woocommerce User-Agent 😊

```js
import Vue from 'vue'
import axios from 'axios'
import WooCommerceRestApi from '@woocommerce/woocommerce-rest-api'

/**
 * New JavaScript library for WooCommerce REST API,
 * supports CommonJS (CJS) and Embedded System Module (ESM).
 * @see https://www.npmjs.com/package/@woocommerce/woocommerce-rest-api#esm-example
 */
Vue.prototype.$WC = new WooCommerceRestApi({
  url: process.env.NUXT_ENV_BASE_PATH,
  consumerKey: process.env.NUXT_ENV_WOO_CONSUMER_KEY,
  consumerSecret: process.env.NUXT_ENV_WOO_CONSUMER_SECRET,
  version: 'wc/v3',
})


// Custom interceptor to remove woocommerce custom User-Agent (not allowed in Chrome/Safari)
axios.interceptors.request.use(function (config) {
  const { headers = {} } = config || {}
  if (headers['User-Agent']) delete config.headers['User-Agent']

  return config
})
```
