### ISSUE TITLE
Authorization Headers

### ISSUE THREAD

**Issue by malebolgia** [woocommerce/woocommerce-rest-api-js-lib#41]
I am using https://wordpress.org/plugins/jwt-authentication-for-wp-rest-api/ , I think this conflict with WooCommerce Auth headers, is there any other way I can authenticate CK_KEY and CK_SECRET instead of Authorization headers, using this lib?

![image](https://user-images.githubusercontent.com/922854/68122104-8e31d400-ff44-11e9-80e4-99f267d9170b.png)

Reviewing also https://github.com/axios/axios#request-config I might get answer here.

**Comment by climba03003** [comment]
When the Authorization header is conflict with JWT Authentication. You may consider to use Query String instead of Header to authenticate.
You may enable the this behavior by passing ```queryStringAuth: true``` in the ```WooCommerceRestApi``` options.

Sample Code:
```javascript
const api = new WooCommerceRestApi({
  url: "http://example.com",
  consumerKey: "ck_XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
  consumerSecret: "cs_XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
  version: "wc/v3",
  queryStringAuth: true
});
```

**Comment by malebolgia** [comment]
Works well, thanks climba03003
